environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.continuous-integration\\appveyor\\run_with_env.cmd"
#    QUEST_CACHE_DIR: quest_test_cache
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

cache:
  - "%QUEST_CACHE_DIR%"

build: false

install:
  # Install miniconda using a powershell script.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
#  - "conda update -q conda"
  - "conda info -a"
  - ps: "(Get-Content conda_environment.yml).replace('python=3', \"python=$env:PYTHON_VERSION\") | Set-Content conda_environment.yml"
  - ps: "If ($env:PYTHON_VERSION -eq '2.7') {(Get-Content conda_environment.yml).replace('# - futures', '- futures') | Set-Content conda_environment.yml}"
  - "conda env create -q -n test-environment -f conda_environment.yml"
  - "activate test-environment"
  - "python setup.py install"

test_script:
  - "%CMD_IN_ENV% pytest test -s -vv"
