# conda environment file for python 3, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py3_conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: quest

channels:
    - conda-forge
    - erdc

dependencies:
    - python=3
    # - futures  # for python 2 compatibility

    # core dependencies
    - click
    - distributed>=1.18
    - fiona
    - gdal
    - geojson
    - libgdal  # to ensure it comes from conda-forge
    - peewee
    - pandas<=0.22.0
    - geopandas
    - jinja2
    - jupyter
    - matplotlib
    - numpy
    - param
    - pint
    - pony<=0.7.1
    - psutil
    - pyyaml
    - rasterio
    - requests
    - sortedcollections
    - tornado
    - ulmo>=0.8.3.2
    - werkzeug

    # test dependencies
    - pytest-cov
    - coveralls

    # docs dependencies
    - sphinx
    - sphinx_rtd_theme

    # plugin dependencies
    - hs_restclient
    - girder-client
    - terrapin
    - ncep_client
    - pillow
