name: dsl

channels:
    - ioos

dependencies:
    - gdal
    - fiona>=1.5.1
    - rasterio>=0.23.0
    - numpy
    - geojson
    - jsonschema
    - ulmo>=0.8.1
    - pyoos
    - pyyaml
    - matplotlib>=1.4.0
    - click
    - pip:
      - json-rpc
      - stevedore
