services:
    usgs-nwis-iv: data_services_library.services.usgs_nwis:UsgsNwisIV
    usgs-nwis-dv: data_services_library.services.usgs_nwis:UsgsNwisDV
    ncdc-ghcn: data_services_library.services.ncdc_ghcn:NcdcGhcn
    ncdc-gsod: data_services_library.services.ncdc_gsod:NcdcGsod
    example-points: data_services_library.services.example:ExamplePoints
    example-polys: data_services_library.services.example:ExamplePolys
    example-vitd: data_services_library.services.example:ExampleVITD
    iraq-vitd: data_services_library.services.iraq_demo:IraqVITD
    iraq-agc-tlidar: data_services_library.services.iraq_demo:IraqAGCTLidar
    iraq-agc-alidar: data_services_library.services.iraq_demo:IraqAGCALidar
    chesapeake-elevation: data_services_library.services.chesapeake_demo:ChesapeakeVTK


collections:
    usgs: []

filters:
    vitd-basic: data_services_library.filters.vitd:Basic