# conda environment file for python 2, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py2_conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: quest

channels:
    - conda-forge
    - defaults

dependencies:
    - python=2
    - futures
    - fiona
    - rasterio
    - gdal
    - numpy
    - geojson
    - jinja2
    - ulmo>=0.8.3.2
    - pyyaml
    - matplotlib
    - click
    - werkzeug
    - peewee
    - stevedore
    - geopandas
    - distributed>=1.18
    - psutil
    - pint
    - pony
    - tornado
    - pytest-cov
    - param
    - sphinx_rtd_theme
    - hs_restclient