services:
    usgs-nwis-iv: data_services_library.services.usgs_nwis:UsgsNwisIV
    usgs-nwis-dv: data_services_library.services.usgs_nwis:UsgsNwisDV
    ncdc-ghcn: data_services_library.services.ncdc_ghcn:NcdcGhcn
    ncdc-gsod: data_services_library.services.ncdc_gsod:NcdcGsod
    example-points: data_services_library.services.example:ExamplePoints
    example-polys: data_services_library.services.example:ExamplePolys

collections:
    usgs: []